# Generated by Django 4.1.3 on 2022-11-01 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='year_opened',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 1, 11, 38, 37, 380067, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
