# Generated by Django 4.1.3 on 2022-11-01 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shop_year_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='year_opened',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 1, 11, 43, 54, 714120, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
