# Generated by Django 4.1.3 on 2022-11-01 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_year_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='year_opened',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 1, 14, 18, 51, 696229, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
