# Generated by Django 4.1.3 on 2022-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_year_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='year_opened',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
