# Generated by Django 4.1.3 on 2022-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_fruit_alter_shop_code_weeklysales_shopoverheads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
