# Generated by Django 4.1.3 on 2022-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_weeklysales_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysales',
            name='date',
            field=models.DateField(verbose_name='pub_date'),
        ),
    ]
