# Generated by Django 4.1.3 on 2022-11-08 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_alter_weeklysales_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='fruitsales',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.fruit'),
        ),
        migrations.AlterField(
            model_name='shopoverheads',
            name='overhead_type',
            field=models.CharField(choices=[('PERS', 'personnel'), ('PREM', 'premises'), ('OTHER', 'other overheads')], max_length=10),
        ),
        migrations.AlterField(
            model_name='weeklysales',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop'),
        ),
    ]
