# Generated by Django 4.1.3 on 2022-11-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_weeklysales_file_alter_uploadfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
