# Generated by Django 4.1.3 on 2022-11-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_fruit_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='units',
        ),
    ]
