# Generated by Django 4.1.3 on 2022-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_remove_fruit_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
